version: '3'

services:

  db:
    image: postgres:latest
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - db_nw
      
  flask:
    build: ./flask
    volumes:
      - ./flask/:/opt/services/flaskapp/src
    networks:
      - db_nw
      - web_nw
    depends_on:
      - db
      
  nginx:
    image: nginx:latest 
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - web_nw
    depends_on: 
      - flask
      
networks:
  db_nw:
    driver: bridge
  web_nw:
    driver: bridge
volumes:
  dbdata: